FROM node:18-alpine AS base

WORKDIR /usr/src/app

COPY package*.json ./

RUN yarn install --production 

COPY . .


RUN npx prisma generate

ENV NODE_ENV=production

EXPOSE 8000

CMD ["yarn", "dev"]
